[project]
name = "romjax"
version = "0.0.1"
description = "Tools for reduced-order modeling"
authors = [
    {name = "Joshua Eckels", email = "eckelsjd@umich.edu"},
]
dependencies = [
    "numpy>=2.0",
    "matplotlib>=3.9",
    "h5py>=3.14",
    "pydantic>=2.12.5",
    "pyyaml>=6.0.3",
    "lineax>=0.1.0",
    "optimistix>=0.1.0",
    "optax>=0.2.8",
    "equinox>=0.13.6",
    "jaxtyping>=0.3.9",
    "networkx>=3.6.1",
    "alive-progress>=3.3.0",
    "jax>=0.9.1",
    "orbax-checkpoint>=0.11.39",
    "loguru>=0.7.3",
]
requires-python = ">=3.12"
readme = "README.md"
license = {text = "MIT"}
keywords = []
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research"
]

[project.urls]
Repository = "https://github.com/eckelsjd/romjax.git"

[project.scripts]
task = "romjax.task_cli:main"
romx = "romjax.romx_cli:main"

[project.optional-dependencies]
cu12 = [
    "jax[cuda12]>=0.9.1",
]
cu13 = [
    "jax[cuda13]>=0.9.1",
]

[build_system]
requires = ["uv_build>=0.10.8,<0.11.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.6",
    "pre-commit>=3.8",
    "commitizen>=3.29",
    "pyproject-runner>=0.3.0",  # Usage: rr <task> <args>
]
test = [
    "pytest>=7.4",
    "pytest-cov>=4.1",
]

[tool.pyproject-runner.tasks]
test = { cmd = "pytest --cov=romjax --cov-report html:htmlcov tests", cwd = "!" }
lint = { cmd = "ruff check src tests", cwd = "!" }

[tool.uv]
package = true

# [tool.uv.sources]
# optimistix = { path = "../optimistix", editable = true }

[tool.ruff.lint]
select = ['E', 'F', 'I']
ignore = ['E731']  # allow lambda definitions

[tool.ruff]
line-length = 120
extend-exclude = ["*.ipynb"]

[tool.pytest.ini_options]
filterwarnings = [
    "ignore:.*'asyncio.iscoroutinefunction' is deprecated.*:DeprecationWarning",
]

[tool.commitizen]
version_scheme = "pep440"
version_provider = "pep621"
version_files = ["src/romjax/__init__.py:__version__"]
update_changelog_on_bump = true
tag_format = "v$version"
changelog_file = "CHANGELOG.md"
major_version_zero = true
annotated_tag = true
post_bump_hooks = ["git push --follow-tags"]
