mplstyle: romjax.stix
gridplot:
  subplot_size_in: [5, 4]
  scheme: dark
  global_plot_kwargs: { lw: 3 }
  animate_opts:
    progress_callback: bar
    fps: 15
    blit: true
logger: [ poisson.log ]
progress_bar:
  theme: smooth