!romx:DataGeneration
routine_config: config/common.yml
root: data
write_policy: reuse
graph: config/graph.yml

datasets:
  train:
    poisson:
      input_samples: 250
      outputs_per_input: 10
      input_seed: 0
      output_seed: 1
      batch_size: 16
    compression:
      loader:
        root: data/train
        datasets:
          poisson: { kind: implicit, max_samples: 500 }
      gather_paths: [poisson, outputs]
      compression: { energy_tol: 0.99 }
      filename: poisson_pod.npz
      write_policy: overwrite
    galerkin:
      samples: 500
      seed: 2
      batch_size: 4
      write_policy: overwrite
  validation:
    poisson:
      input_samples: 25
      outputs_per_input: 5
      input_seed: 3
      output_seed: 4
      batch_size: 1
