!romx:DataGeneration
routine_config: config/common.yml
root: data
write_policy: reuse
graph: config/graph.yml

datasets:
  train:
    poisson:
      input_samples: 250
      outputs_per_input: 10
      input_seed: 0
      output_seed: 1
      batch_size: 1
    compression:
      loader: !romx:DataLoader
        root: data/train
        datasets:
          poisson: { kind: implicit, max_samples: 500 }
      gather_paths: [poisson, outputs]
      compression: { energy_tol: 0.95 }
      filename: poisson_pod.npz
      write_policy: overwrite
    galerkin:
      samples: 200
      seed: 2
      batch_size: 32
  validation:
    poisson:
      input_samples: 25
      outputs_per_input: 10
      input_seed: 3
      output_seed: 4
      batch_size: 1
