!romx:DataGeneration
routine_config: config/common.yml
root: dataset
write_policy: reuse
graph: config/graph.yml
datasets:
  train:
    poisson:
      input_samples: 250
      outputs_per_input: 10
      input_seed: 0
      output_seed: 1
  validation:
    poisson:
      input_samples: 25
      outputs_per_input: 10
      input_seed: 2
      output_seed: 3