!romx:Train
routine_config: config/common.yml
root: train
write_policy: overwrite
graph: config/graph.yml
init_seed: 10

loss: !romx:GraphLoss
  - { callable: reconstruction, path: [coordinate transform] }
  # - { function: tikhonov, weight: 0.01, batch_reduce: null }
init_params: !romx:PyTreeSampler
  coordinate transform:
    call_args:
      name: LinearProjection
      kwargs:
        latent: !romx:GraphRef [edges, galerkin, latent_dim]
        dof: 1024
  residual transform: coordinate transform
optimizer: { name: adam, args: [ 0.1 ] }

dataloader: !romx:DataLoader 
  root: data/train
  datasets:
    poisson: { batch_size: 16, shuffle_seed: 1 }
    # galerkin: { batch_size: 32, shuffle_seed: 1 }
test: !romx:GraphTest
  loader:
    root: data/validation
    datasets:
      poisson: { batch_size: 32, shuffle_seed: 0 }
  terms:
    - { callable: reconstruction, path: [coordinate transform] }

termination: 
  max_steps: 800
  max_runtime: 300
  grad_tol: 1e-5
diagnostics:
  log_interval: null
  plot_interval: 50
  test_interval: 50
  live_plot: true
checkpointer:
  save_decision_policy: { name: FixedIntervalPolicy, args: [100] }
  preservation_policy: 
    name: AnyPreservationPolicy
    args: [ [{ name: LatestN, args: [10] }, {name: EveryNSteps, args: [100] }] ]
