!romx:DataGeneration
root: demo/dataset
graph: demo/poisson_graph.yml
train:
  input_samples: 64
  outputs_per_input: 4
  input_seed: 0
  output_seed: 1
validation:
  input_samples: 32
  outputs_per_input: 2
  input_seed: 2
  output_seed: 3
write_policy: reuse
batch_size: 4
