!romx:GenDataConfig
root: demo/dataset
graph: demo/poisson_graph.yml
train:
  input_samples: 256
  outputs_per_input: 16
  input_seed: 0
  output_seed: 1
validation:
  input_samples: 256
  outputs_per_input: 8
  input_seed: 2
  output_seed: 3
dataset_policy: reuse
batch_size: 16
